name: Deploy Backend to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO }}

    - name: Build Docker image
      run: docker build -t wp-backend .

    - name: Tag Docker image
      run: docker tag wp-backend:latest ${{ secrets.AWS_ECR_REPO }}:latest

    - name: Push Docker image
      run: docker push ${{ secrets.AWS_ECR_REPO }}:latest

    - name: Update ECS service
      run: |
        aws ecs update-service \
          --cluster wp-backend-cluster \
          --service wp-backend-service \
          --force-new-deployment
